version: '3'
services:

  client-app:
    build:
      context: ./client-app
    networks:
      - graphqlmesh
    environment:
      - SERVER_ADDRESS=server-app
      - INSTANA_DEV=1
      - INSTANA_AGENT_HOST=agent

  server-app:
    build:
      context: ./server-app
    networks:
      graphqlmesh:
        aliases:
          - server-app
    environment:  
      - INSTANA_DEV=1
      - INSTANA_AGENT_HOST=agent
    expose:
      - "8080"

  agent:
    image: instana/agent:test
    pid: "host"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev:/dev
      - /sys:/sys
      - /var/log:/var/log
    networks:
      graphqlmesh:
        aliases:
          - instana-agent
    environment:
      - INSTANA_AGENT_ENDPOINT=${agent_endpoint:?No agent endpoint provided}
      - INSTANA_AGENT_ENDPOINT_PORT=${agent_endpoint_port:-443}
      - INSTANA_AGENT_KEY=${agent_key:?No agent key provided}
      - INSTANA_AGENT_ZONE=${agent_zone:-graphql-demo}
    expose:
      - "42699"

networks:
  graphqlmesh: {}
